# Generated by Django 4.2.29 on 2026-04-12 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0006_add_engineer_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('case_id', models.CharField(blank=True, default='', help_text='HP Case ID. Required for in-warranty cases.', max_length=100)),
                ('case_type', models.CharField(choices=[('iw', 'In-Warranty'), ('oow', 'Out-of-Warranty')], max_length=5)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('part_allocated', 'Part Allocated'), ('transfer_requested', 'Transfer Requested'), ('engineer_assigned', 'Engineer Assigned'), ('in_progress', 'In Progress'), ('service_completed', 'Service Completed'), ('pending_replenishment', 'Pending Replenishment'), ('replenishment_ordered', 'Replenishment Ordered'), ('stock_replenished', 'Stock Replenished'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='created', max_length=30)),
                ('region', models.CharField(choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(blank=True, default='', max_length=50)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('model_number', models.CharField(blank=True, default='', max_length=100)),
                ('part_number', models.CharField(blank=True, default='', max_length=100)),
                ('part_name', models.CharField(blank=True, default='', max_length=255)),
                ('qty_used', models.IntegerField(default=1)),
                ('source_region', models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], default='', help_text='Region the part was sourced from (may differ if transferred).', max_length=20)),
                ('resolution_summary', models.TextField(blank=True, default='')),
                ('service_notes', models.TextField(blank=True, default='')),
                ('proof_uploaded', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_buffer_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buffer_cases', to='authenticate.engineer')),
            ],
            options={
                'verbose_name': 'Buffer Case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BufferStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('print_head', 'Print Head'), ('toner', 'Toner Cartridge'), ('fuser', 'Fuser Unit'), ('drum', 'Drum Unit'), ('formatter', 'Formatter Board'), ('scanner', 'Scanner Assembly'), ('adf', 'ADF Assembly'), ('roller', 'Roller Kit'), ('power_supply', 'Power Supply'), ('other', 'Other')], default='other', max_length=30)),
                ('brand', models.CharField(default='HP', max_length=100)),
                ('region', models.CharField(choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], max_length=20)),
                ('qty_on_hand', models.IntegerField(default=0)),
                ('qty_reserved', models.IntegerField(default=0)),
                ('qty_in_transit', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=2)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('storage_location', models.CharField(blank=True, default='', max_length=100)),
                ('provided_by', models.CharField(default='HP', max_length=100)),
                ('last_replenished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buffer Stock Item',
                'ordering': ['region', 'part_number'],
                'unique_together': {('part_number', 'region')},
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('region', models.CharField(choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buffer_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_order', to='buffer_stock.buffercase')),
                ('buffer_stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_orders', to='buffer_stock.bufferstockitem')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_orders', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Replenishment Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OOWApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approver_role', models.CharField(blank=True, default='', help_text='Role of the approver at the time of action.', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oow_approvals', to=settings.AUTH_USER_MODEL)),
                ('buffer_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oow_approval', to='buffer_stock.buffercase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oow_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OOW Approval',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='InterRegionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('source_region', models.CharField(choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], max_length=20)),
                ('destination_region', models.CharField(choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL)),
                ('buffer_stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='buffer_stock.bufferstockitem')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_receipts', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='buffer_stock.buffercase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inter-Region Transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='buffer_proofs/%Y/%m/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('buffer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='buffer_stock.buffercase')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Proof',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='buffercase',
            name='buffer_stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='buffer_stock.bufferstockitem'),
        ),
        migrations.AddField(
            model_name='buffercase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_buffer_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BufferAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('stock_created', 'Stock Created'), ('stock_updated', 'Stock Updated'), ('stock_adjusted', 'Stock Adjusted'), ('case_created', 'Case Created'), ('case_status_changed', 'Case Status Changed'), ('case_closed', 'Case Closed'), ('oow_requested', 'OOW Approval Requested'), ('oow_approved', 'OOW Approved'), ('oow_rejected', 'OOW Rejected'), ('transfer_requested', 'Transfer Requested'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('transfer_received', 'Transfer Received'), ('replenishment_created', 'Replenishment Created'), ('replenishment_received', 'Replenishment Received'), ('proof_uploaded', 'Proof Uploaded'), ('part_allocated', 'Part Allocated'), ('part_released', 'Part Released')], max_length=30)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.IntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('region', models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buffer Audit Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
