# Generated by Django 5.2.14 on 2026-05-17 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HPStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Case ID')),
                ('work_order_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Work Order ID')),
                ('delivery_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Delivery No')),
                ('service_event_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Service Event No')),
                ('material_order_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Material Order No')),
                ('hp_sales_order_no', models.CharField(blank=True, default='', max_length=100, verbose_name='HP Sales Order No')),
                ('gvrma_no', models.CharField(blank=True, default='', max_length=100, verbose_name='GVRMA No')),
                ('region', models.CharField(blank=True, default='', max_length=20, verbose_name='Region')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='PENDING', max_length=30, verbose_name='Status')),
                ('engineer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Engineer Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hp_stock_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HP Stock Item',
                'verbose_name_plural': 'HP Stock Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
