# Generated by Django 5.2.14 on 2026-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='transition_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Transition History'),
        ),
    ]
