# Generated by Django 5.2.14 on 2026-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0002_hpstockitem_transition_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpstockitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('UNUSED_RETURN', 'Unused Return'), ('DEFECTIVE_RETURN', 'Defective Return'), ('CLOSED', 'Closed')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
