# Generated by Django 5.2.14 on 2026-05-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0004_alter_hpstockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='engineer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Engineer Phone'),
        ),
    ]
