# Generated by Django 5.2.14 on 2026-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0006_alter_hpstockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_description',
            field=models.TextField(blank=True, default='', verbose_name='Part Description'),
        ),
    ]
