# Generated by Django 5.2.14 on 2026-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0007_hpstockitem_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='inventory_details',
            field=models.TextField(blank=True, default='', verbose_name='Inventory Details'),
        ),
    ]
