# Generated by Django 5.2.14 on 2026-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0008_hpstockitem_inventory_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='opencall_case_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Opencall Case Details'),
        ),
    ]
