# Generated by Django 5.2.14 on 2026-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0009_hpstockitem_opencall_case_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hpstockitem',
            options={'ordering': ['-case_created_time', '-created_at'], 'verbose_name': 'HP Stock Item', 'verbose_name_plural': 'HP Stock Items'},
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='case_created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Case Created Time'),
        ),
    ]
