# Generated by Django 5.2.14 on 2026-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0010_alter_hpstockitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpstockitem',
            name='case_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Case ID'),
        ),
    ]
