# Generated by Django 5.2.14 on 2026-07-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0011_alter_hpstockitem_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpstockitem',
            name='case_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Case ID'),
        ),
        migrations.CreateModel(
            name='HPStockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='hp_stock_images/', verbose_name='Good Part Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_part_images', to='hp_stock.hpstockitem')),
            ],
            options={
                'verbose_name': 'HP Stock Good Part Image',
                'verbose_name_plural': 'HP Stock Good Part Images',
                'ordering': ['created_at'],
            },
        ),
    ]
