# Generated by Django 5.2.14 on 2026-07-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0012_alter_hpstockitem_case_id_hpstockimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpstockitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Stock Entry'), ('STOCK_CHECK', 'Stock Check'), ('GOOD_PART_PHOTO', 'Good Part Photo'), ('ISSUED', 'Part Taken by Engineer'), ('WORK_STATUS', 'Work Status'), ('UNUSED_RETURN', 'Unused Part'), ('DEFECTIVE_RETURN', 'Old/Defective Part'), ('HANDOVER', 'Part Handover by Engineer'), ('CLOSED', 'Close the Case')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='HPStockImage',
        ),
    ]
