# Generated by Django 5.2.14 on 2026-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0013_alter_hpstockitem_status_delete_hpstockimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='good_part_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Good Part Photo'),
        ),
    ]
