# Generated by Django 5.2.14 on 2026-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0014_hpstockitem_good_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='return_part_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Part Photo'),
        ),
        migrations.AlterField(
            model_name='hpstockitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Stock Entry'), ('STOCK_CHECK', 'Stock Check'), ('GOOD_PART_PHOTO', 'Good Part Photo'), ('ISSUED', 'Part Taken by Engineer'), ('WORK_STATUS', 'Work Status'), ('UNUSED_RETURN', 'Unused Part'), ('DEFECTIVE_RETURN', 'Old/Defective Part'), ('HANDOVER', 'Part Handover by Engineer'), ('RETURN_PART_PHOTO', 'Return Part Photo'), ('CLOSED', 'Close the Case')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
