# Generated by Django 5.2.14 on 2026-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0015_hpstockitem_return_part_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpstockitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Stock Entry'), ('STOCK_CHECK', 'Stock Check'), ('GOOD_PART_PHOTO', 'Good Part Photo'), ('ISSUED', 'Part Taken by Engineer'), ('WORK_STATUS', 'Work Status'), ('UNUSED_RETURN', 'Unused Part'), ('DEFECTIVE_RETURN', 'Old/Defective Part'), ('HANDOVER', 'Part Handover by Engineer'), ('RETURN_PART_PHOTO', 'Return Part Photo'), ('DC_CUT_REQUEST', 'DC Cut Request'), ('CLOSED', 'Close the Case')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
