# Generated by Django 5.2.14 on 2026-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0016_alter_hpstockitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPStockRMAPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Part Number')),
                ('description', models.TextField(blank=True, default='', verbose_name='Part Description')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Price')),
                ('hsn_code', models.CharField(blank=True, default='', max_length=50, verbose_name='HSN Code')),
                ('igst', models.CharField(blank=True, default='', max_length=10, verbose_name='IGST')),
                ('cgst', models.CharField(blank=True, default='', max_length=10, verbose_name='CGST')),
                ('sgst', models.CharField(blank=True, default='', max_length=10, verbose_name='SGST')),
                ('eosl_flag', models.CharField(blank=True, default='', max_length=10, verbose_name='EOSL Flag')),
                ('validity', models.DateField(blank=True, null=True, verbose_name='Validity')),
                ('parts_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Parts Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HP Stock RMA Part',
                'verbose_name_plural': 'HP Stock RMA Parts',
                'ordering': ['part_number'],
            },
        ),
    ]
