# Generated by Django 5.2.14 on 2026-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0017_hpstockrmapart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpstockrmapart',
            name='part_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Part Number'),
        ),
    ]
