# Generated by Django 5.2.14 on 2026-07-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0018_alter_hpstockrmapart_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='dc_cut_request_message',
            field=models.TextField(blank=True, default='', verbose_name='DC Cut Request Message'),
        ),
    ]
