# Generated by Django 5.2.14 on 2026-07-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0019_hpstockitem_dc_cut_request_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='dc_cut_approved',
            field=models.BooleanField(default=False, verbose_name='DC Cut Approved'),
        ),
    ]
