# Generated by Django 5.2.14 on 2026-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0020_hpstockitem_dc_cut_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='dc_cut_chat',
            field=models.JSONField(blank=True, default=list, verbose_name='DC Cut Chat Logs'),
        ),
    ]
