# Generated by Django 5.2.14 on 2026-07-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0021_hpstockitem_dc_cut_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='good_part_image_back',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Good Part Back Photo'),
        ),
    ]
