# Generated by Django 5.2.12 on 2026-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0012_alter_hpstockitem_case_id'),
        ('hp_stock', '0022_hpstockitem_good_part_image_back'),
    ]

    operations = [
    ]
