# Generated by Django 5.2.12 on 2026-07-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0024_strip_signed_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='good_part_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Good Part Number'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_order_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Part Order Number'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_shipment_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Part Shipment Status'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='so_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SO Number'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='warranty_trade',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Warranty/Trade'),
        ),
    ]
