# Generated by Django 5.2.14 on 2026-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0025_hpstockitem_good_part_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpencallPartsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='Report Date')),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Region')),
                ('count', models.IntegerField(default=0, verbose_name='Parts Call Count')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenCall Parts Count',
                'verbose_name_plural': 'OpenCall Parts Counts',
                'ordering': ['-report_date', 'region'],
                'unique_together': {('report_date', 'region')},
            },
        ),
    ]
