# Generated by Django 5.2.14 on 2026-07-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0026_opencallpartscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='return_box_back_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Box Back Photo'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_box_corner_bottom_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Box Corner Bottom Photo'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_box_corner_left_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Box Corner Left Photo'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_box_corner_right_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Box Corner Right Photo'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_box_corner_top_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Box Corner Top Photo'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_box_front_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Box Front Photo'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_option_image_1',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Option Photo 1'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_option_image_2',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Option Photo 2'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_option_image_3',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Option Photo 3'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='return_part_ct_image',
            field=models.FileField(blank=True, null=True, upload_to='hp_stock_images/', verbose_name='Return Part CT Photo'),
        ),
    ]
