# Generated by Django 5.2.14 on 2026-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0027_hpstockitem_return_box_back_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpencallActivePartCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='Report Date')),
                ('case_id', models.CharField(db_index=True, max_length=100, verbose_name='Case ID')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'OpenCall Active Part Case',
                'verbose_name_plural': 'OpenCall Active Part Cases',
                'unique_together': {('report_date', 'case_id')},
            },
        ),
    ]
