# Generated by Django 5.2.14 on 2026-07-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0028_opencallactivepartcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='sn_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SN Number'),
        ),
    ]
