# Generated by Django 5.2.12 on 2026-08-12 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_stock', '0029_hpstockitem_sn_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hpstockitem',
            name='flex_installed_status',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Flex Installed Status'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received At'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hp_stock_received_marks', to=settings.AUTH_USER_MODEL, verbose_name='Received Marked By User'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_received_source',
            field=models.CharField(blank=True, choices=[('', '—'), ('FLEX', 'Flex sync'), ('MANUAL', 'Marked at the desk')], default='', max_length=10, verbose_name='Received Marked By'),
        ),
        migrations.AddField(
            model_name='hpstockitem',
            name='part_received_status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('RECEIVED', 'Received'), ('IN_TRANSIT', 'In Transit')], db_index=True, default='', max_length=20, verbose_name='Part Received Status'),
        ),
        migrations.CreateModel(
            name='HPStockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_spare_only', models.BooleanField(default=False, help_text='Hide part rows that Flex still reports as in transit.', verbose_name='Show received spares only')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hp_stock_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HP Stock Settings',
                'verbose_name_plural': 'HP Stock Settings',
            },
        ),
    ]
