"""
Django settings for ainventory project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file (never committed).
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-eqem)23jqdvtj64m85suojxx-=bt^q@i-mvkg8hpot_-)6$*2d",
)

# DEBUG must be False in production. Controlled via the DEBUG env var.
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "inventory.bazhilgroups.in,inventoryback.systimus.in,localhost,127.0.0.1").split(",")


INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "corsheaders",
    "authenticate",
    "material",
    "ticket",
    "customer",
    "parts",
    "quotation",
    "procurement",
    "buffer_stock",
    "invoice",
    "rest_framework",
    "rest_framework.authtoken",
    "hp_stock",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ainventory.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ainventory.wsgi.application"


if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(conn_max_age=600),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves static files (incl. the admin) straight from gunicorn,
# compressed, so the app works with DEBUG=False without a separate web server.
_STATICFILES_BACKEND = "whitenoise.storage.CompressedStaticFilesStorage"

# --- Media / file storage -------------------------------------------------
# Uploaded files (e.g. HP stock part photos) go to AWS S3 when USE_S3 is
# enabled; otherwise they fall back to local disk for development.
USE_S3 = os.environ.get("USE_S3", "False").lower() in ("true", "1", "yes")

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "ap-south-1")

    # Public objects served over permanent, non-expiring URLs (images must
    # stay viewable indefinitely — signed URLs cap out at AWS's 7-day limit).
    # Public read is granted by the bucket policy; ACLs are disabled on the
    # bucket ("Bucket owner enforced"), so we never send per-object ACLs.
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    # Use the regional endpoint + SigV4 so signed URLs validate without a
    # redirect (the global s3.amazonaws.com endpoint breaks signatures for
    # regions like ap-south-1).
    AWS_S3_ENDPOINT_URL = os.environ.get(
        "AWS_S3_ENDPOINT_URL", f"https://s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    )
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "virtual"

    _DEFAULT_STORAGE_BACKEND = "storages.backends.s3.S3Storage"
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
else:
    _DEFAULT_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {"BACKEND": _DEFAULT_STORAGE_BACKEND},
    "staticfiles": {"BACKEND": _STATICFILES_BACKEND},
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Production security --------------------------------------------------
# Applied only when DEBUG is off. Assumes TLS is terminated by the reverse
# proxy (Traefik/Dokploy), which forwards X-Forwarded-Proto.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", 0))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Off by default to avoid redirect loops behind a proxy; enable via env.
    SECURE_SSL_REDIRECT = os.environ.get(
        "SECURE_SSL_REDIRECT", "False"
    ).lower() in ("true", "1", "yes")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "https://inventory.systimus.in,https://inventory-frontend-sigma-one.vercel.app,http://localhost:5173,http://127.0.0.1:5173",
).split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "https://inventory.bazhilgroups.in,https://inventoryback.systimus.in,https://inventory.systimus.in,https://inventory-frontend-sigma-one.vercel.app",
).split(",")

# Fast2SMS configuration
# Get your API key from https://www.fast2sms.com/
FAST2SMS_API_KEY = os.environ.get("FAST2SMS_API_KEY", "ihUR6HeXIvCc1ZK0jkrTun9F7BAMSDb4mtl5YO2oWPpdg8EsfNVJczFE04qLbSND8s17gjRxwnHai2B3")


UNFOLD = {
    "SITE_TITLE": "RenderWays Admin",
    "SITE_HEADER": "RenderWays",
    "SITE_SUBHEADER": "Inventory Management",
    "SITE_SYMBOL": "inventory_2",
    "SITE_ICON": {
        "light": "/static/books/img/logo.png",
        "dark": "/static/books/img/logo.png",
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    # "STYLES": [
    #     "/static/books/css/admin-custom.css",
    # ],
    "SITE_DROPDOWN": [
        {
            "title": "Dashboard",
            "icon": "dashboard",
            "link": "/admin/",
        },
        {
            "title": "Material Records",
            "icon": "inventory",
            "link": "/admin/material/materialtrack/",
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": "/admin/auth/user/",
                        "permission": "ainventory.unfold_permissions.is_superuser",
                    },
                    {
                        "title": "Groups",
                        "icon": "admin_panel_settings",
                        "link": "/admin/auth/group/",
                        "permission": "ainventory.unfold_permissions.is_superuser",
                    },
                    {
                        "title": "Tokens",
                        "icon": "key",
                        "link": "/admin/authtoken/tokenproxy/",
                        "permission": "ainventory.unfold_permissions.is_superuser",
                    },
                    {
                        "title": "Material Tracking Records",
                        "icon": "inventory_2",
                        "link": "/admin/material/materialtrack/",
                        "permission": "ainventory.unfold_permissions.can_access_material",
                    },
                ],
            }
        ],
    },
    "COLORS": {
        "base": {
            "50": "#f7f8fe",
            "100": "#eef1fb",
            "200": "#dde4f6",
            "300": "#c2cdea",
            "400": "#98a8d8",
            "500": "#7181c2",
            "600": "#5463a2",
            "700": "#404a7d",
            "800": "#2d355b",
            "900": "#1c223d",
            "950": "#101425",
        },
        "primary": {
            "50": "#f2f4ff",
            "100": "#e7e9ff",
            "200": "#cfd5ff",
            "300": "#aeb8ff",
            "400": "#8692fb",
            "500": "#5f69f3",
            "600": "#4a4fdc",
            "700": "#343393",
            "800": "#2b2b78",
            "900": "#25275f",
            "950": "#17183b",
        },
        "font": {
            "subtle-light": "#66708b",
            "subtle-dark": "#b8c4e6",
            "default-light": "#21263d",
            "default-dark": "#eaf0ff",
            "important-light": "#11172d",
            "important-dark": "#ffffff",
        },
    },
}
