"""
Django settings for ainventory project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-eqem)23jqdvtj64m85suojxx-=bt^q@i-mvkg8hpot_-)6$*2d"
DEBUG = True
ALLOWED_HOSTS = ["*"]


INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "corsheaders",
    "authenticate",
    "material",
    "rest_framework",
    "rest_framework.authtoken",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ainventory.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ainventory.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

CORS_ALLOW_ALL_ORIGINS = True


UNFOLD = {
    "SITE_TITLE": "RenderWays Admin",
    "SITE_HEADER": "RenderWays",
    "SITE_SUBHEADER": "Inventory Management",
    "SITE_SYMBOL": "inventory_2",
    "SITE_LOGO": {
        "light": "/static/books/img/logo.png",
        "dark": "/static/books/img/logo.png",
    },
    "SITE_ICON": {
        "light": "/static/books/img/logo.png",
        "dark": "/static/books/img/logo.png",
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "STYLES": [
        "/static/books/css/admin-custom.css",
    ],
    "SITE_DROPDOWN": [
        {
            "title": "Dashboard",
            "icon": "dashboard",
            "link": "/admin/",
        },
        {
            "title": "Material Records",
            "icon": "inventory",
            "link": "/admin/material/materialtrack/",
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "admin_panel_settings",
                        "link": "/admin/auth/group/",
                    },
                    {
                        "title": "Tokens",
                        "icon": "key",
                        "link": "/admin/authtoken/tokenproxy/",
                    },
                    {
                        "title": "Material Tracking Records",
                        "icon": "inventory_2",
                        "link": "/admin/material/materialtrack/",
                    },
                ],
            }
        ],
    },
    "COLORS": {
        "base": {
            "50": "#fcfcff",
            "100": "#f7f7fb",
            "200": "#ececf4",
            "300": "#d9d9e7",
            "400": "#acaec4",
            "500": "#7d8098",
            "600": "#595d77",
            "700": "#43475d",
            "800": "#2d3044",
            "900": "#191b28",
            "950": "#0d0f18",
        },
        "primary": {
            "50": "#fff0f7",
            "100": "#ffd8e9",
            "200": "#ffafd1",
            "300": "#ff77b0",
            "400": "#ff438f",
            "500": "#f01976",
            "600": "#d80d66",
            "700": "#b20754",
            "800": "#8f0b47",
            "900": "#770d3d",
            "950": "#520324",
        },
        "font": {
            "subtle-light": "#6b7280",
            "subtle-dark": "#c9d0df",
            "default-light": "#1d1d22",
            "default-dark": "#edf1ff",
            "important-light": "#0f0f13",
            "important-dark": "#ffffff",
        },
    },
}
