# Generated by Django 5.2.12 on 2026-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('cust_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Contact')),
                ('case_id', models.CharField(max_length=100, unique=True, verbose_name='Case ID')),
                ('so_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='SO#')),
                ('warranty', models.BooleanField(default=False, verbose_name='Warranty')),
                ('issue', models.TextField(blank=True, null=True, verbose_name='Issue')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part #')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial #')),
                ('qty', models.IntegerField(default=0, verbose_name='Qty')),
                ('hp_part_in_date', models.DateField(blank=True, null=True, verbose_name='HP Part In Date')),
                ('aging', models.IntegerField(blank=True, null=True, verbose_name='Aging (Days)')),
                ('out_date', models.DateField(blank=True, null=True, verbose_name='Out Date')),
                ('collector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Collector')),
                ('in_date', models.DateField(blank=True, null=True, verbose_name='In Date')),
                ('receiver', models.CharField(blank=True, max_length=200, null=True, verbose_name='Receiver')),
                ('used_part', models.BooleanField(default=False, verbose_name='Used Part')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Material Tracking Record',
                'verbose_name_plural': 'Material Tracking Records',
                'ordering': ['-out_date', '-in_date'],
            },
        ),
    ]
