# Generated by Django 5.2.12 on 2026-04-04 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_materialtrack_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtrack',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material Tracking Record', 'verbose_name_plural': 'Material Tracking Records'},
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='aging',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='hp_part_in_date',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='in_date',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='product',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='so_number',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='used_part',
        ),
        migrations.RemoveField(
            model_name='materialtrack',
            name='warranty',
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='call_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('taken_for_service', 'Taken for Service')], default='pending', max_length=20, verbose_name='Call Status'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='condition_received',
            field=models.TextField(blank=True, null=True, verbose_name='Condition Received'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='ct_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CT Code'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='cust_address',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='customer_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Comments'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='engineer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Engineer Name'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='failure_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Failure Code'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='hp_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HP ID'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='installed_part_sno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Installed Part S.No.'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='issue_description',
            field=models.TextField(blank=True, null=True, verbose_name='Issue Description'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='part_description',
            field=models.TextField(blank=True, null=True, verbose_name='Part Description'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='part_usage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Part Usage'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='product_name',
            field=models.CharField(default='', max_length=200, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='region',
            field=models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram')], help_text="Auto-set from the sub-admin's region on create.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='removed_part_sno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Removed Part S.No.'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='resolution_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resolution Summary'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='service_type',
            field=models.CharField(choices=[('warranty', 'Warranty'), ('non_warranty', 'Non Warranty'), ('doc', 'DOC'), ('amc', 'AMC'), ('rental', 'Rental')], default='warranty', max_length=20, verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='so_req_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='So. No./Req ID'),
        ),
        migrations.AddField(
            model_name='materialtrack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='case_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='cust_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='cust_name',
            field=models.CharField(default='', max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product/Part No.'),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='materialtrack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
