# Generated by Django 5.2.12 on 2026-04-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtrack',
            name='region',
            field=models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], help_text="Auto-set from the sub-admin's region on create.", max_length=20, null=True),
        ),
    ]
