# Generated by Django 5.2.12 on 2026-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_userprofile_region_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram')], help_text='Required for non-admin roles.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('engineer', 'Engineer'), ('receptionist', 'Receptionist'), ('cc_team', 'CC Team'), ('super_admin', 'Super Admin'), ('sub_admin', 'Sub Admin')], default='engineer', max_length=20),
        ),
    ]
