# Generated by Django 5.2.14 on 2026-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_sections',
            field=models.JSONField(blank=True, default=list, help_text='Allowed section paths or labels for managers.'),
        ),
    ]
