# Generated by Django 4.2.29 on 2026-04-09 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, verbose_name='Part Number')),
                ('part_name', models.CharField(max_length=255, verbose_name='Part Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('general_name', models.CharField(blank=True, default='', max_length=255, verbose_name='General Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buffer_parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buffer Part',
                'verbose_name_plural': 'Buffer Parts',
                'ordering': ['-created_at'],
            },
        ),
    ]
