# Generated by Django 4.2.29 on 2026-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_add_buffer_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferpart',
            name='region',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Region'),
        ),
    ]
