# Generated by Django 5.2.13 on 2026-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_bufferpart_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferpart',
            name='status',
            field=models.CharField(choices=[('BUFFER_IN', 'BUFFER In'), ('OUT', 'Out'), ('DEFECTIVE_RETURN', 'Defective Return'), ('UNUSED_RETURN', 'Unused Return'), ('REORDER', 'Reorder'), ('PART_RECEIVED', 'Part Received'), ('CLOSED', 'Closed')], default='BUFFER_IN', max_length=30, verbose_name='Status'),
        ),
    ]
