# Generated by Django 5.2.14 on 2026-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_bufferpart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferpart',
            name='engineer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Engineer Phone'),
        ),
        migrations.AlterField(
            model_name='bufferpart',
            name='status',
            field=models.CharField(choices=[('BUFFER_IN', 'BUFFER In'), ('PART_AVAILABILITY_CHECK', 'Part Availability Check'), ('USABLE_READY_TO_USE', 'Usable (Good Part) ready to use'), ('DEFECTIVE_NOT_READY_TO_USE', 'Defective (Faulty Part) not ready to use'), ('OUT', 'Part Taken by Engineer'), ('WORK_STATUS', 'Work Status'), ('DEFECTIVE_RETURN', 'Defective Return'), ('UNUSED_RETURN', 'Unused Return'), ('PART_HANDOVER_BY_ENGINEER', 'Part Handover by Engineer'), ('REORDER', 'Reorder'), ('PART_RECEIVED', 'Part Received'), ('CLOSED', 'Closed')], default='BUFFER_IN', max_length=30, verbose_name='Status'),
        ),
    ]
