# Generated by Django 4.2.29 on 2026-04-06 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Ticket Number')),
                ('cust_name', models.CharField(default='', max_length=255, verbose_name='Customer Name')),
                ('cust_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Number')),
                ('cust_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email')),
                ('cust_address', models.TextField(blank=True, null=True, verbose_name='Customer Address')),
                ('product_name', models.CharField(default='', max_length=200, verbose_name='Product Name')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Number')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('case_id', models.CharField(default='', max_length=100, unique=True, verbose_name='Case ID')),
                ('condition_received', models.TextField(blank=True, null=True, verbose_name='Condition Received')),
                ('service_type', models.CharField(choices=[('warranty', 'Warranty'), ('non_warranty', 'Non Warranty'), ('doc', 'DOC'), ('amc', 'AMC'), ('rental', 'Rental')], default='warranty', max_length=20, verbose_name='Service Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Priority')),
                ('issue_description', models.TextField(blank=True, null=True, verbose_name='Issue Description')),
                ('current_status', models.CharField(choices=[('cso_created', 'CSO Created'), ('assigned', 'Assigned'), ('diagnosis', 'Diagnosis'), ('part_requested', 'Part Requested'), ('part_approved', 'Part Approved'), ('quotation_sent', 'Quotation Sent'), ('cx_pending', 'Customer Pending'), ('cx_approved', 'Customer Approved'), ('cx_rejected', 'Customer Rejected'), ('part_ordered', 'Part Ordered'), ('part_received', 'Part Received'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('closed', 'Closed'), ('under_observation', 'Under Observation')], default='cso_created', max_length=30, verbose_name='Current Status')),
                ('requires_parts', models.BooleanField(default=False, verbose_name='Requires Parts')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product/Part No.')),
                ('part_usage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Part Usage')),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Failure Code')),
                ('part_description', models.TextField(blank=True, null=True, verbose_name='Part Description')),
                ('qty', models.IntegerField(default=1, verbose_name='Qty')),
                ('ct_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='CT Code')),
                ('so_req_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='So. No./Req ID')),
                ('removed_part_sno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Removed Part S.No.')),
                ('installed_part_sno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Installed Part S.No.')),
                ('resolution_summary', models.TextField(blank=True, null=True, verbose_name='Resolution Summary')),
                ('engineer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Engineer Name')),
                ('hp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='HP ID')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('customer_comments', models.TextField(blank=True, null=True, verbose_name='Customer Comments')),
                ('region', models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram')], max_length=20, null=True, verbose_name='Region')),
                ('otp_verified', models.BooleanField(default=False, verbose_name='OTP Verified')),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP Verified At')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Arrival Date')),
                ('target_completion', models.DateField(blank=True, null=True, verbose_name='Target Completion')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Current Assignee')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('sla_minutes', models.IntegerField(blank=True, null=True)),
                ('is_breached', models.BooleanField(default=False)),
                ('breach_minutes', models.IntegerField(default=0)),
                ('responsible_role', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Timeline Entry',
                'verbose_name_plural': 'Ticket Timeline Entries',
                'ordering': ['entered_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('service_type', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('sla_minutes', models.IntegerField()),
                ('responsible_role', models.CharField(max_length=30)),
                ('warning_at_percent', models.IntegerField(default=75)),
                ('escalation_after_mins', models.IntegerField(blank=True, null=True)),
                ('escalation_to_role', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
                'unique_together': {('status', 'service_type', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='DelayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('responsible_role', models.CharField(max_length=30)),
                ('sla_minutes', models.IntegerField()),
                ('actual_minutes', models.IntegerField()),
                ('delay_minutes', models.IntegerField()),
                ('delay_category', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_delays', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_records', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_records', to='ticket.ticket')),
                ('timeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_records', to='ticket.tickettimeline')),
            ],
            options={
                'verbose_name': 'Delay Record',
                'verbose_name_plural': 'Delay Records',
                'ordering': ['-id'],
            },
        ),
    ]
