# Generated by Django 5.2.12 on 2026-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='case_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cust_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Product Name'),
        ),
    ]
