# Generated by Django 5.2.12 on 2026-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_case_id_alter_ticket_cust_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_order',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Work Order'),
        ),
    ]
