# Generated by Django 5.2.12 on 2026-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_location_ticket_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='region',
            field=models.CharField(blank=True, choices=[('vellore', 'Vellore'), ('salem', 'Salem'), ('chennai', 'Chennai'), ('kanchipuram', 'Kanchipuram'), ('hosur', 'Hosur')], max_length=20, null=True, verbose_name='Region'),
        ),
    ]
