# Generated by Django 5.2.12 on 2026-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
