# Generated by Django 4.2.29 on 2026-04-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_add_engineer_model'),
        ('ticket', '0005_delayrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned At'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='authenticate.engineer', verbose_name='Assigned Engineer'),
        ),
    ]
