# Generated by Django 4.2.29 on 2026-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_add_assigned_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='form_number',
            field=models.CharField(blank=True, help_text='Region-based sequential number, e.g. SAL-2026-0001', max_length=30, null=True, unique=True, verbose_name='Form Number'),
        ),
        migrations.CreateModel(
            name='RegionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Region Counter',
                'unique_together': {('region', 'year')},
            },
        ),
    ]
