# Generated by Django 4.2.29 on 2026-04-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_add_form_number_and_region_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cso_date',
            field=models.DateField(blank=True, null=True, verbose_name='CSO Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='case_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Case ID'),
        ),
    ]
