# Generated by Django 4.2.29 on 2026-04-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket_cso_date_alter_ticket_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('warranty', 'Warranty'), ('non_warranty', 'Non Warranty'), ('doa', 'DOA'), ('amc', 'AMC'), ('rental', 'Rental'), ('trade', 'Trade')], default='warranty', max_length=20, verbose_name='Service Type'),
        ),
    ]
