# Generated by Django 5.2.13 on 2026-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('warranty', 'Warranty'), ('non_warranty', 'Non Warranty'), ('doa', 'DOA'), ('amc', 'AMC'), ('rental', 'Rental'), ('trade', 'Trade'), ('rca', 'RCA'), ('accessories', 'Accessories')], default='warranty', max_length=20, verbose_name='Service Type'),
        ),
    ]
