# Generated by Django 5.2.13 on 2026-05-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_activitycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycharge',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_charges', to='ticket.ticket', verbose_name='Ticket'),
        ),
    ]
