# Generated by Django 5.2.14 on 2026-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_activitycharge_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cso_image',
            field=models.FileField(blank=True, null=True, upload_to='cso_images/', verbose_name='CSO Image'),
        ),
    ]
