# Generated by Django 5.2.14 on 2026-05-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_ticket_cso_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='part_request_image',
            field=models.FileField(blank=True, null=True, upload_to='part_request_images/', verbose_name='Part Request Image'),
        ),
    ]
