# Generated by Django 5.2.14 on 2026-05-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_ticket_part_request_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPartRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='part_request_images/', verbose_name='Part Request Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_request_images', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Part Request Image',
                'verbose_name_plural': 'Ticket Part Request Images',
                'ordering': ['created_at'],
            },
        ),
    ]
